config/routes.rb
Rails.application.routes.draw do
  resource :session
  resources :users
  resources :pieces do
    resources :registrations
  end
  root 'static_pages#home'
  get 'about' => 'static_pages#about'
  get 'contact' => 'static_pages#contact'
end

app/models/piece.rb
# piece class
class Piece < ActiveRecord::Base
  has_attached_file :picture, styles: { medium: "400x400>", thumb: "200x200>" }
  # piece validations
  before_save { |piece| piece.medium = piece.medium.downcase }
  before_save { |piece| piece.title = piece.title.strip }

  validates :title, :medium, :size, presence: true, length: { within: 1..40 }
  validates :description, length: { within: 1..500 }
  validates :rental_price_per_day, :rental_price_per_week, :rental_price_per_month, :sale_price, numericality: { greater_than_or_equal_to: 0 }
  validates :available, :sold, inclusion: { in: [true, false] }
  validates_attachment_content_type :picture, content_type: /\Aimage\/.*\Z/
  # piece class methods

  # Piece#order_by takes a parameter and orders pieces based on that parameter.
  # It defaults to ordering by last_updated if unknown parameter is passed in.
  def self.order_by(command)
    case command
    when 'last_updated' then order('updated_at desc')
    when 'last_added' then order('created_at desc')
    else order('updated_at desc')
    end
  end

  has_many :registrations, dependent: :destroy
end

app/models/registration.rb
class Registration < ActiveRecord::Base
  before_save { |registration| registration.email = registration.email.downcase }
  before_save { |registration| registration.name = registration.name.strip }
  belongs_to :piece

  validates :name, length: { within: 1..25 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, format: { with: VALID_EMAIL_REGEX }
  validates :phone_number, numericality: { only_integer: true }, length: { is: 10, message: 'should be 10 digits starting with area code'}
  validates :message, presence: false
  validates :neighborhood, presence: true
  validates :zip_code, length: { is: 5, message: 'should be 5 digits' }
  validates :interested_in_rental, :interested_in_purchase, inclusion: { in: [true, false] }
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  validates :password, length: { minimum: 8, allow_blank: true }
  validates :first_name, :last_name, presence: true
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
end

app/controllers/pieces_controller.rb
# pieces controller
class PiecesController < ApplicationController
  def index
    @pieces = Piece.order_by('last_updated')
  end

  def show
    @piece = Piece.find(params[:id])
  end

  def edit
    @piece = Piece.find(params[:id])
  end

  def update
    @piece = Piece.find(params[:id])
    @piece.update(piece_params)
    if @piece.save
      flash[:notice] = "#{@piece.title} has been successfully updated"
      redirect_to piece_path(@piece.id)
    else
      render :edit
    end
  end

  def new
    @piece = Piece.new
  end

  def create
    @piece = Piece.create(piece_params)
    if @piece.save
      redirect_to piece_path(@piece.id)
      flash[:notice] = "#{@piece.title} has been successfully added to the #{$SITE_NAME} gallery"
    else render :new
    end
  end

  def destroy
    @piece = Piece.find(params[:id])
    title = @piece.title
    @piece.destroy
    redirect_to pieces_url, notice: "#{title} was successfully removed from the #{$SITE_NAME} gallery"
  end

  private

  def piece_params
    params.require(:piece).permit(:title, :description, :medium, :size, :rental_price_per_day, :rental_price_per_week, :rental_price_per_month, :sale_price, :available, :sold, :picture)
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < ApplicationController
  before_action :set_piece

  def index
    @registrations = @piece.registrations
  end

  def new
    @registration = @piece.registrations.new
  end

  def create
    @registration = @piece.registrations.new(registration_params)
    if @registration.save
      flash[:notice] = "Your registration for #{@piece.title} has been sent to the artist!"
      redirect_to piece_path(@piece.id)
    else
      render :new
    end
  end

  def destroy
    @registration = @piece.registrations.find((params[:id]))
    name = @registration.name
    @registration.destroy
    redirect_to piece_registrations_url, notice: "#{name}'s request was successfully removed!"
  end

  private

  def registration_params
    params.require(:registration).permit(:name, :email, :phone_number, :message, :interested_in_rental, :interested_in_purchase, :neighborhood, :zip_code, :organization)
  end

  def set_piece
    @piece = Piece.find(params[:piece_id])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      flash[:notice] = "Welcome back, #{user.first_name}! You're currently signed in."
      redirect_to user_path(user.id)
    else
      flash.now[:notice] = "Hmm... we can't find a user with that email/password combination"
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:notice] = "You're all signed out. We'll see you again soon!"
    redirect_to root_url
  end
end

app/controllers/static_pages_controller.rb
# static pages controller
class StaticPagesController < ApplicationController
  def home
  end

  def about
  end

  def contact
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      # uncomment below if you want users signed in upon account creation
      # session[:user_id] = @user.id
      redirect_to root_path, notice: "Your account was successfully created!"
    else
      render :new
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    if @user.save
      redirect_to users_path, notice: "Your account has been successfully updated!"
    else
      render :edit
    end
  end

  def destroy
    @user = User.find(params[:id])
    first_name = @user.first_name
    @user.destroy
    session[:user_id] = nil
    redirect_to root_path, notice: "We're sorry to see you go, #{first_name}! If you need anything from us again don't hesitate to reach out :)"
  end

private

  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :portfolio_url, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
# application helper module
module ApplicationHelper
  $SITE_NAME = 'Arch City Art'

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
end

app/helpers/pieces_helper.rb
# pieces helper module
module PiecesHelper
  def availability_status(piece)
    if piece.available && !piece.sold
      'Available for both rental and purchase.'
    elsif !piece.available && !piece.sold
      'Unavailable at the moment'
    else
      'Sold'
    end
  end
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
  def rental_or_purchase_for(request)
    if (request.interested_in_rental == true)  && (request.interested_in_purchase == true)
      "#{request.name} is interested in both renting and purchasing this piece."
    elsif (request.interested_in_rental == true) && (request.interested_in_purchase == false)
      "#{request.name} is interested in renting this piece."
    elsif (request.interested_in_rental == false) && (request.interested_in_purchase == true)
      "#{request.name} is interested in purchasing this piece."
    else
      "#{request.name} did not indicate a preference for rental or purchase."
    end
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def membership_created_on(user)
    "#{user.created_at.strftime("%B #{user.created_at.day.ordinalize}, %Y")}"
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= "#{$SITE_NAME}" %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class='container'>
  <p><%= link_to("Home", root_path) %>
    | <%= link_to("About", about_path) %>
    | <%= link_to("Contact", contact_path) %>
    <% if current_user %>
    | <%= link_to("Logout", session_path, method: :delete) %>
    | <%= link_to "Your dashboard", current_user %></p>
    <% else %>
    | <%= link_to("Artist Log In", new_session_path) %></p>
    <% end %>
  <%= render 'shared/flashes' %>
  <%= yield %>
</div>

</body>
</html>

app/views/pieces/_form.html.erb
<%= form_for(@piece) do |f| %>
  <%= render 'shared/errors', object: @piece %>
  <h3><%= f.label :title %></h3>
  <%= f.text_field :title %><br>

  <h3><%= f.label :medium %></h3>
  <%= f.text_field :medium %><br>

  <h3><%= f.label :description %></h3>
  <%= f.text_area :description, placeholder: 'Keep it simple, but significant. Less than 500 characters.' %><br>

  <h3><%= f.label :size %></h3>
  <%= f.text_field :size, placeholder: '16in x 24in' %><br>

  <h3><%= f.label :rental_price_per_day %></h3>
  <%= f.number_field :rental_price_per_day %><br>

  <h3><%= f.label :rental_price_per_week %></h3>
  <%= f.number_field :rental_price_per_week %><br>

  <h3><%= f.label :rental_price_per_month %></h3>
  <%= f.number_field :rental_price_per_month %><br>

  <h3><%= f.label :sale_price %></h3>
  <%= f.number_field :sale_price %><br>

  <h3><%= f.label :picture %></h3>
  <%= f.file_field :picture %>

  <h4>Quick heads up: make sure both boxes below are not checked at the same time.</h4>
  <p><%= f.label "Mark piece as available: " %><%= f.check_box :available? %></p>
  <p><%= f.label "Mark piece as sold: " %>  <%= f.check_box :sold? %></p>

  <%= f.submit %>
<% end %>

app/views/pieces/index.html.erb
<h1>We found <%= pluralize(@pieces.size, 'piece') %> for you to check out today: </h1>
<% @pieces.each do |p| %><br>
  <h1><em><%= link_to(p.title, piece_path(p.id)) %></em> (<em><%= p.medium %></em>)</h1>
  <%= image_tag p.picture.url(:thumb) %>
  <p><em><%= p.description %></em></p>
  <p><em><%= p.size %></em></p>
  <p><em><%= number_to_currency(p.rental_price_per_day) %> per day / <%= number_to_currency(p.rental_price_per_week) %> per week / <%= number_to_currency(p.rental_price_per_month) %> per month</em></p>
  <p><em>Sale price: <%= number_to_currency(p.sale_price) %></p></em>
  <p><em>Status: <%= availability_status(p) %></em</p><br>
  <h4><em>Updated <%= time_ago_in_words(p.updated_at) %> ago</em></h4>
<% end %>

app/views/pieces/new.html.erb
<h1>Add your new piece here</h1>
<%= render 'form' %>

app/views/pieces/show.html.erb
<h1><%= @piece.title %>
  <% if @piece.registrations.size > 0 %>
    has <%= link_to("#{pluralize(@piece.registrations.size, 'registration')}", piece_registrations_path(@piece)) %><br>
  <% end %>
</h1>

<%= image_tag @piece.picture.url(:medium) %>

<h3><em><%= @piece.medium %></em></h3>

<p><em><%= @piece.description %></em></p>

<p><em><%= @piece.size %></em></p>

<p><em><%= number_to_currency(@piece.rental_price_per_day) %> per day / <%= number_to_currency(@piece.rental_price_per_week) %> per week / <%= number_to_currency(@piece.rental_price_per_month) %> per month</em></p>

<p><em>Sale price: <%= number_to_currency(@piece.sale_price) %></p></em>

<p><em>Status: <%= availability_status(@piece) %></em</p>

<h4>Updated <%= time_ago_in_words(@piece.updated_at) %> ago</h4>
<% if @piece.sold == false  %>
  <%= link_to("Register to rent or purchase #{@piece.title}", new_piece_registration_path(@piece.id)) %><br>
<% else %>
  <p>This piece is no longer available for rental or purchase</p>
<% end %>
<%= link_to("Edit #{@piece.title}'s status", edit_piece_path(@piece.id)) %><br>
<%= link_to "Remove #{@piece.title} from #{$SITE_NAME}", piece_path(@piece.id), method: :delete, data: { confirm: "Removing '#{@piece.title}' is permanent. Please click 'OK' to confirm removal or 'Cancel' to go back." } %><br>
<%= link_to("Go back", pieces_path) %>

app/views/shared/_errors.html.erb
<% if object.errors.any? %>
  <section id="errors">
    <header>
      <h2>
        Oops! Your <%= object.class.name.titleize.downcase %> could not be saved.
      </h2>
      <h3>
        Please correct the following <%= pluralize(object.errors.count, "error") %>:
      </h3>
    </header>
    <ul>
      <% object.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </section>
<% end %>

app/views/shared/_flashes.html.erb
<%=  flash[:notice] ? flash[:notice] : nil %>

app/views/static_pages/about.html.erb
<h1><%= link_to("View our member artists", users_path) %></h1>

app/views/static_pages/home.html.erb
<h1><%= link_to("Enter #{$SITE_NAME}", pieces_path) %></h1>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <%= render 'shared/errors', object: @user %>
  <h3><%= f.label :first_name %></h3>
  <%= f.text_field :first_name %><br>

  <h3><%= f.label :last_name %></h3>
  <%= f.text_field :last_name %><br>

  <h3><%= f.label :email %></h3>
  <%= f.text_field :email %><br>

  <h3><%= f.label :portfolio_url, "Portfolio Site" %></h3>
  <%= f.text_field :portfolio_url %><br>

  <h3><%= f.label :password %></h3>
  <%= f.password_field :password %><br>

  <h3><%= f.label :password_confirmation, "Confirm your password" %></h3>
  <%= f.password_field :password_confirmation %><br>

  <%= f.submit %>
<% end %>

app/views/users/edit.html.erb
<%= render 'form' %>

app/views/users/index.html.erb
<h1>Your <%= "#{$SITE_NAME}" %> member artists</h1>
<% @users.shuffle.each do |u| %>
  <h2><%= u.first_name %> <%= u.last_name %></h2>
  <p><em>Member since <%= membership_created_on(u) %></em></p>
<% end %>

app/views/users/new.html.erb
<%= render 'form' %>

app/views/users/show.html.erb
<h1><%= "#{@user.first_name}'s dashboard as of today at" %> <%= "#{Time.now.strftime("%I:%M %p")}" %></h1>
<h3><%= link_to("Add a piece to the gallery", new_piece_path) %></h3>
<h3><%= link_to("Edit your account", edit_user_path) %></h3>
<%= link_to "Delete your #{$SITE_NAME} account", user_path(@user.id), method: :delete, data: { confirm: "Deleting your account is permanent. Please click 'OK' to confirm removal or 'Cancel' to go back" } %>